#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required

git:
  submodules: false

###################
# global settings #
###################

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "IJtre+FcQfrrqdusN2Kb9RHv39IQOKzmmiJKXqzNzTL/NCn/U22DCNwW3w0vD+YuqOPJtfh9/zgZ6fuEPtQlUm0YcXCFISoy88E7vwQqidIlipnr0PXIhStEOakNn3AAj9IKwd8cU0oGYK4kAs7mZJTWlOAaJwYe4/huUHwsB2EBQYt5ijEVyYwDX/qQADjZpn9RY/JECgdklJnLjVluUR7hXf3TsC8JG7818lW5rIhLhyrJL5Un+oVzS82AdLsy11DeLPFHTtvsNIh/tPJg1CVgSvKYrwtrsS2TvUpO+pJKEQZk5cTlNXOm2euqSoUDVNUCvUlQb6zGWknFu+NJ4azrY79OaveFRlGcHT0/ulhADyGI0WoD75Yf0MJbc3vfzccFW2kQnz5bVR/M4IO1MxClH8gkXNofuZYQoLE8TyDhqpG2FRHkn4c4e8yMpER0f8Pyq7oh3+NXIvGsyNgxBDiSLpTyCYn/US8vZZ+ZXPWVgTMtcX0mabrJAHsPUuTiDET2rhnj4BUrjRkQ7iRNhvoJCgIo0l54+Femr5NkiE73aCsxgXL4vQHGxO6VHkMVI5dj+meAraugqfBruLaWm5JnYp6cFYEAbqmzlJZPkunNv/i3JFhm2Wl8FGGXt3g79IiZ5EAbR3Bl+mh348/WfxUG9rLnX+RqZ09MkVw5xDE="


##################
# Before install #
##################
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libeigen3-dev

################
# build matrix #
################
matrix:
  include:
    # Coverity scan 
    - compiler: gcc
      env:
        - COMPILER=g++-5
        - SPECIAL=coverity
      before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'valgrind', 'libeigen3-dev']
        coverity_scan:
          project:
            name: "cb-geo/lbm-dem"
            description: "LBM-DEM Coverity scan build submitted via Travis CI"
          notification_email: cued.geomechanics@gmail.com
          build_command_prepend: "cmake ."
          build_command:   "make"
          branch_pattern: coverity_scan
   
    # Codecov
    - compiler: gcc
      env:
        - COMPILER=g++-5
        - SPECIAL=codecoverage
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'ruby']
      before_script:
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
      after_success:
        - rm -rf ./* && cmake .. -DENABLE_COVERAGE=On
        - make clean && make
        - ./lbmdem
        - ./lbmdemtest
        - make gcov
        - make lcov
        - bash <(curl -s https://codecov.io/bash) -X gcov


    # Valgrind and cppcheck
    - compiler: gcc
      env:
        - COMPILER=g++-5
        - SPECIAL=valgrind
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cppcheck', 'valgrind']
      after_success:
        - valgrind --error-exitcode=1 --leak-check=full ./lbmdem
        - valgrind --error-exitcode=1 --leak-check=full ./lbmdemtest
        - cd .. && cppcheck --enable=warning --inconclusive --force --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1

    # Clang static analysis
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - CONFIG=scan-build
        - ASAN="ON"
        - MSAN="ON"
        - TSAN="ON"
        - UBSAN="ON"
        - STATIC_ANALYZER="ON"
        - CLANG_FORMAT="ON"
        - CLANG_TIDY="ON"
      after_success:
        - scan-build cmake ..
        - scan-build make

################
# build script #
################

script:
    - mkdir build
    - cd build
    - cmake ..
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi
    - ctest -VV -S

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lbmdem

