version: 2
jobs:
  build:
    working_directory: /home/cbgeo/research/lbm-dem
    docker:
      - image: cbgeo/lbmdem
    steps:
      - checkout
      # Configure CMake and run
      - run:
          name: Build LBM
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On .. && make clean && make -j8


